/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  EvidenceAssessment,
  EvidenceFusionResult,
  calculateEvidenceFusion,
} from '../../domain/evidenceFusion.ts';

/**
 * Gate 2F.3: Synthetic Evidence Assessments for Pollution Event VS-E001 (Zone VS-Z07).
 *
 * IMPORTANT SCIENTIFIC DISCLAIMER:
 * These assessment values (quality, agreement, freshness) are strictly DEMO/SYNTHETIC
 * inputs calibrated to the synthetic pollution scenario for VS-E001 / VS-Z07.
 * They represent illustrative scenario parameters, NOT measured scientific ground truth
 * or calibrated physical sensor confidence.
 *
 * NOTE ON AI-IMAGE EVIDENCE:
 * 'ai-image' is deliberately EXCLUDED from these available assessments because no real
 * Gemini Vision analysis exists for this synthetic baseline event. Per scientific
 * governance boundaries, AI visual interpretation must only be assessed when an authentic
 * Gemini analysis payload has been generated from an actual evidence image.
 */

export const VS_E001_EVIDENCE_ASSESSMENTS: EvidenceAssessment[] = [
  {
    // Ground sensor station spike at VS-Z07 (PM2.5: 248.5 µg/m³, SO2 surge: 94.2 µg/m³)
    // DEMO / SYNTHETIC input values — not measured scientific confidence
    source: 'ground-sensor',
    available: true,
    quality: 0.90,
    agreement: 0.88,
    freshness: 0.95,
  },
  {
    // Orbital thermal-anomaly & dense smoke aerosol signature at 28.388°N, 77.317°E
    // DEMO / SYNTHETIC input values — not measured scientific confidence
    source: 'satellite',
    available: true,
    quality: 0.82,
    agreement: 0.85,
    freshness: 0.80,
  },
  {
    // Meteorological consistency: Sustained NW wind vector at 18.5 km/h driving downwind transport
    // DEMO / SYNTHETIC input values — not measured scientific confidence
    source: 'meteorology',
    available: true,
    quality: 0.85,
    agreement: 0.82,
    freshness: 0.90,
  },
  {
    // Clustered citizen reports: 14 report signals in 3km radius reporting heavy plumes and sulfurous odors
    // DEMO / SYNTHETIC input values — not measured scientific confidence
    source: 'citizen-report',
    available: true,
    quality: 0.70,
    agreement: 0.78,
    freshness: 0.85,
  },
];

/**
 * Deterministic evidence fusion result for event VS-E001.
 * Computed strictly via algorithmic weighted fusion, never generated by Gemini.
 */
export const VS_E001_FUSION_RESULT: EvidenceFusionResult =
  calculateEvidenceFusion(VS_E001_EVIDENCE_ASSESSMENTS);
