/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Gate 2F.1 & Gate 2F.2: Evidence Fusion Domain
 *
 * Rules:
 * - quality, agreement, freshness are normalized scores from 0.0 to 1.0.
 * - score is deterministic and strictly computed by algorithms, never generated by Gemini.
 * - Gemini provides structured visual interpretation only and cannot determine fusion score or event verification.
 */

export type EvidenceSource =
  | 'citizen-report'
  | 'ai-image'
  | 'ground-sensor'
  | 'satellite'
  | 'meteorology';

export interface EvidenceAssessment {
  source: EvidenceSource;
  available: boolean;
  /** Normalized score from 0.0 to 1.0 */
  quality: number;
  /** Normalized score from 0.0 to 1.0 */
  agreement: number;
  /** Normalized score from 0.0 to 1.0 */
  freshness: number;
}

export interface EvidenceFusionResult {
  assessments: EvidenceAssessment[];
  /** Deterministic fusion score, never generated by Gemini */
  score: number;
  status: 'insufficient' | 'low' | 'moderate' | 'high';
}

export const EVIDENCE_SOURCE_WEIGHTS: Record<EvidenceSource, number> = {
  'citizen-report': 0.10,
  'ai-image': 0.15,
  'ground-sensor': 0.30,
  'satellite': 0.25,
  'meteorology': 0.20,
};

function validateUnitInterval(value: unknown, fieldName: string, source: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value < 0 || value > 1) {
    throw new RangeError(
      `Invalid ${fieldName} for ${source}: expected a finite number between 0 and 1, got ${value}`
    );
  }
  return value;
}

/**
 * Pure function to calculate deterministic multi-source evidence fusion.
 *
 * For available evidence only:
 * sourceScore = quality * 0.4 + agreement * 0.4 + freshness * 0.2
 * Final score = weighted average of available sourceScores.
 *
 * Status thresholds:
 * - <0.30 = 'low'
 * - <0.60 = 'moderate'
 * - >=0.60 = 'high'
 * - Fewer than 2 independent evidence sources = 'insufficient'
 */
export function calculateEvidenceFusion(
  assessments: EvidenceAssessment[]
): EvidenceFusionResult {
  if (!Array.isArray(assessments)) {
    throw new TypeError('assessments must be an array');
  }

  // Validate all numeric inputs are 0–1
  for (const assessment of assessments) {
    validateUnitInterval(assessment.quality, 'quality', assessment.source);
    validateUnitInterval(assessment.agreement, 'agreement', assessment.source);
    validateUnitInterval(assessment.freshness, 'freshness', assessment.source);
  }

  const availableAssessments = assessments.filter((a) => a.available);
  const uniqueAvailableSources = new Set(availableAssessments.map((a) => a.source));

  if (availableAssessments.length === 0) {
    return {
      assessments,
      score: 0,
      status: 'insufficient',
    };
  }

  let totalWeightedScore = 0;
  let totalWeight = 0;

  for (const assessment of availableAssessments) {
    const weight = EVIDENCE_SOURCE_WEIGHTS[assessment.source] ?? 0;
    const sourceScore =
      assessment.quality * 0.4 +
      assessment.agreement * 0.4 +
      assessment.freshness * 0.2;

    totalWeightedScore += sourceScore * weight;
    totalWeight += weight;
  }

  const rawScore = totalWeight > 0 ? totalWeightedScore / totalWeight : 0;
  const score = Math.max(0, Math.min(1, rawScore));

  let status: EvidenceFusionResult['status'];

  if (uniqueAvailableSources.size < 2) {
    status = 'insufficient';
  } else if (score < 0.30) {
    status = 'low';
  } else if (score < 0.60) {
    status = 'moderate';
  } else {
    status = 'high';
  }

  return {
    assessments,
    score,
    status,
  };
}
